import wallet1 from "../../public/assets/img/wallet/wallet1.png";
import wallet2 from "../../public/assets/img/wallet/wallet2.png";
import wallet3 from "../../public/assets/img/wallet/wallet3.png";
import wallet4 from "../../public/assets/img/wallet/wallet4.png";
import wallet5 from "../../public/assets/img/wallet/wallet5.png";
import wallet6 from "../../public/assets/img/wallet/wallet6.png";
import { WalletConnectData } from "@/interFace/interFace";

export const walletConnect:WalletConnectData[] = [
    {
        walletTitle: "Wallet Connect",
        walletImage: wallet1,
        walletDesc:
            "Sale your single item to increase your currencies that generated by crypto currency.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Metamask",
        walletImage: wallet2,
        walletDesc:
            "Sale your single item to increase your currencies that generated by crypto currency.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Fortmatic",
        walletImage: wallet3,
        walletDesc:
            "Sale your single item to increase your currencies that generated by crypto currency.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Torus",
        walletImage: wallet4,
        walletDesc:
            "Sale your single item to increase your currencies that generated by crypto currency.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Bitski",
        walletImage: wallet5,
        walletDesc:
            "Sale your single item to increase your currencies that generated by crypto currency.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Coinbase",
        walletImage: wallet6,
        walletDesc:
            "Sale your single item to increase your currencies that generated by crypto currency.",
        walletBtn: "Connect",
    },
];

export const dashboardWalletConnect: WalletConnectData[] = [
    {
        walletTitle: "Wallet Connect",
        walletImage: wallet1,
        walletDesc:
            "Easily link your wallet to manage digital assets.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Metamask",
        walletImage: wallet2,
        walletDesc:
            "Access decentralized with your trusted crypto wallet.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Fortmatic",
        walletImage: wallet3,
        walletDesc:
            "Enjoy seamless blockchain interactions with Fortmatic.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Torus",
        walletImage: wallet4,
        walletDesc:
            "Connect instantly using your social media credentials.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Bitski",
        walletImage: wallet5,
        walletDesc:
            "A developer-friendly wallet for streamlined transactions.",
        walletBtn: "Connect",
    },
    {
        walletTitle: "Coinbase",
        walletImage: wallet6,
        walletDesc:
            "Experience secure and efficient crypto transactions.",
        walletBtn: "Connect",
    },
];
